About/urls.py
from django.urls import path
from .views import Aboutview
urlpatterns = [
    path('abouts', Aboutview.as_view(), name='about'),
]

Home/urls.py
from django.urls import path, include
from .views import Homeview
urlpatterns = [
    path('', Homeview.as_view(), name='home'),
]

Products/urls.py
from django.urls import path
from .views import ProductListView, ProductDetailView

app_name = "products"

urlpatterns = [
    path('products', ProductListView.as_view(), name="product"),
    path('detail/<slug:slug>/', ProductDetailView.as_view(), name="detail")
]

accounts/urls.py
from django.urls import path
from .views import login_page, register_page, guest_register_view
from django.contrib.auth.views import LogoutView

app_name = "accounts"

urlpatterns = [
    path('login/', login_page, name="login"),
    path('register/', register_page, name="register"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('guest/register/', guest_register_view, name="guest_register"),

]

carts/urls.py
from django.urls import path
from .views import cart_home, cart_update, checkout_home, checkout_done_view, cart_detail_api_view

app_name = "carts"

urlpatterns = [
    path('cart', cart_home, name="home"),
    path('api/', cart_detail_api_view, name="home_api"),
    path('checkout/', checkout_home, name="checkout"),
    path('update/', cart_update, name="update"),
    path('success/', checkout_done_view, name="success"),
]

About/models.py
from django.db import models

# Create your models here.

Products/models.py
import os
import random
from django.db import models
from django.db.models.signals import pre_save
from Ecommerces.utils import unique_slug_generator
from django.urls import reverse
from django.db.models import Q


def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    name, ext = get_filename_ext(filename)
    new_filename = random.randint(1, 123123123123)
    final_name = f"{new_filename}{ext}"
    return f"products/{final_name}"


class ProductQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(active=True)

    def featured(self):
        return self.filter(featured=True)

    def search(self, query):
        lookups = (
                Q(title__icontains=query) |
                Q(description__icontains=query) |
                Q(price__icontains=query) |
                Q(tag__title__icontains=query)
        )
        return self.filter(lookups).distinct()


class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().active()

    def featured(self):
        return self.get_queryset().featured()

    def get_by_id(self, id):
        qs = self.get_queryset().filter(id=id)  # Products.objects == self.get_queryset()
        if qs.count() == 1:
            return qs.first()
        return None

    def search(self, query):
        return self.get_queryset().active().search(query)


class Product(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(blank=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=20, decimal_places=4, default=39.99)
    image = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    featured = models.BooleanField(default=False)
    active = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    # Manager
    objects = ProductManager()

    def get_absolute_url(self):
        # return f"/products/detail/{self.slug}/"
        return reverse('products:detail', kwargs={"slug": self.slug})

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = "products"
        verbose_name_plural = "Product"


def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(product_pre_save_receiver, sender=Product)  # Signals

carts/models.py
from django.conf import settings
from django.db import models
from Products.models import Product
from django.db.models.signals import pre_save, m2m_changed
from decimal import Decimal

User = settings.AUTH_USER_MODEL


class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get('cart_id', None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = self.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    products = models.ManyToManyField(Product, blank=True)
    subtotal = models.DecimalField(max_digits=30, decimal_places=4, default=0)
    total = models.DecimalField(max_digits=30, decimal_places=4, default=0)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)


def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()


m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)


def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = Decimal(instance.subtotal) * Decimal(1.08)
    else:
        instance.total = 0


pre_save.connect(pre_save_cart_receiver, sender=Cart)

About/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


# Create your views here.


class Aboutview(TemplateView):
    template_name = 'about.html'

Products/views.py
from django.views.generic import ListView, DetailView
from .models import Product
from carts.models import Cart


class ProductListView(ListView):
    queryset = Product.objects.all()
    template_name = "products.html"

    def get_context_data(self, *args, **kwargs):
        context = super(ProductListView, self).get_context_data()
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)
        context['cart'] = cart_obj
        return context


class ProductDetailView(DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)
        context['cart'] = cart_obj
        return context

    template_name = "detail.html"

carts/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from Products.models import Product
from .models import Cart
from orders.models import Order
from accounts.forms import LoginForm, GuestForm
from billing.models import BillingProfile
from addresses.forms import AddressForm
from addresses.models import Address
from decimal import Decimal


def cart_detail_api_view(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    products = [{
        'id': x.id,
        'url': x.get_absolute_url(),
        'title': x.title,
        'price': format(x.price, '.2f')
    } for x in cart_obj.products.all()]
    cart_data = {
        'products': products,
        'subTotal': format(cart_obj.subtotal, '.2f'),
        'total': format(cart_obj.total, '.2f')
    }
    return JsonResponse(cart_data, status=200)


def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    return render(request, "cart.html", {"cart": cart_obj})


def cart_update(request):
    product_id = request.POST.get('product_id')
    if product_id is not None:

        # get product or return cart page
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            # ajax error response
            if request.is_ajax():
                json_data = {
                    'added': False,
                    'removed': False,
                }
                return JsonResponse(json_data, status=409)

            return redirect("carts:home")

        cart_obj, new_obj = Cart.objects.new_or_get(request)

        if product_obj in cart_obj.products.all():
            # remove product cart
            cart_obj.products.remove(product_obj)
            product_added = False
        else:
            # add product cart
            cart_obj.products.add(product_obj)
            product_added = True

        # cart product count update
        request.session['cart_items'] = cart_obj.products.count()

        if request.is_ajax():
            json_data = {
                'added': product_added,
                'removed': not product_added,
                'cartItemCount': cart_obj.products.count(),
            }
            return JsonResponse(json_data, status=200)

    # no product_id in post request
    return redirect("carts:home")


def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    billing_address_id = request.session.get('billing_address_id', None)
    shipping_address_id = request.session.get('shipping_address_id', None)

    if cart_created or cart_obj.products.count() == 0:
        return redirect("carts:home")

    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
    address_qs = None
    if billing_profile is not None:
        if request.user.is_authenticated:
            address_qs = Address.objects.filter(billing_profile=billing_profile)
        order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)

        if shipping_address_id:
            order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
            del request.session['shipping_address_id']
        if billing_address_id:
            order_obj.billing_address = Address.objects.get(id=billing_address_id)
            del request.session['billing_address_id']
        if billing_address_id or shipping_address_id:
            order_obj.save()

    if request.method == 'POST':
        "some check that order is done"
        is_done = order_obj.check_done()
        if is_done:
            order_obj.mark_paid()
            request.session['cart_items'] = 0
            del request.session['cart_id']
            return redirect("carts:success")

    context = {
        'object': order_obj,
        'billing_profile': billing_profile,
        'login_form': LoginForm(),
        'guest_form': GuestForm(),
        'address_form': AddressForm(),
        'address_qs': address_qs,
    }

    return render(request, "carts/checkout.html", context)


def checkout_done_view(request):
    context = {
        "order_code": request.POST.get('order_code')
    }
    return render(request, "carts/checkout-done.html", context)

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content%}

	<!--  about-page -->
	<div class="about">
		<div class="container">
			<h3 class="w3ls-title w3ls-title1">About Smart bazaar</h3>
			<div class="about-text">
				<p>Etiam faucibus viverra libero vel efficitur. Ut semper nisl ut laoreet ultrices. Maecenas dictum arcu purus, sit amet volutpat purus viverra sit amet. Quisque lacinia quam sed tortor interdum, malesuada congue nunc ornare. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In semper lorem eget tortor pulvinar ultricies. Nulla sodales efficitur consequat. Maecenas mi diam, imperdiet consectetur ultricies nec, convallis sit amet turpis.
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tempor vehicula ipsum nec ultrices. Pellentesque sed feugiat sapien.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tempor vehicula ipsum nec ultrices. Pellentesque sed feugiat sapien.  ullamcorper nunc. Aenean eget massa orci. Vivamus vulputate elit at rutrum elementum. Duis sit amet posuere justo, sit amet finibus urna. Aenean elementum diam nec laoreet sodales. Morbi vulputate tempor nisl nec tristique.</p>
				<div class="col-md-3 ftr-top-left about-text-grids">
					<i class="fa fa-shopping-basket" aria-hidden="true"></i>
					<h4>10 Million+ <br>Products</h4>
				</div>
				<div class="col-md-3 ftr-top-left about-text-grids">
					<i class="fa fa-users" aria-hidden="true"></i>
					<h4>50,000 <br> Sellers </h4>
				</div>
				<div class="col-md-3 ftr-top-left about-text-grids">
					<i class="fa fa-credit-card" aria-hidden="true"></i>
					<h4>5 Million <br>Shipments</h4>
				</div>
				<div class="col-md-3 ftr-top-left about-text-grids">
					<i class="fa fa-globe" aria-hidden="true"></i>
					<h4>4000+ <br>Cities</h4>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="history">
				<h3 class="w3ls-title">Our Mission</h3>
				<p>Etiam faucibus viverra libero vel efficitur. Ut semper nisl ut laoreet ultrices. Maecenas dictum arcu purus, sit amet volutpat purus viverra sit amet. Quisque lacinia quam sed tortor interdum, malesuada congue nunc ornare. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In semper lorem eget tortor pulvinar ultricies. Nulla sodales efficitur consequat. Maecenas mi diam, imperdiet consectetur ultricies nec, convallis sit amet turpis.
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tempor vehicula ipsum nec ultrices. Pellentesque sed feugiat sapien.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tempor vehicula ipsum nec ultrices. Pellentesque sed feugiat sapien.  ullamcorper nunc. Aenean eget massa orci. Vivamus vulputate elit at rutrum elementum. Duis sit amet posuere justo, sit amet finibus urna. Aenean elementum diam nec laoreet sodales. Morbi vulputate tempor nisl nec tristique.</p>
				<h3 class="w3ls-title">Our History</h3>
				<p>Etiam faucibus viverra libero vel efficitur. Ut semper nisl ut laoreet ultrices. Maecenas dictum arcu purus, sit amet volutpat purus viverra sit amet. Quisque lacinia quam sed tortor interdum, malesuada congue nunc ornare. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In semper lorem eget tortor pulvinar ultricies. Nulla sodales efficitur consequat. Maecenas mi diam, imperdiet consectetur ultricies nec, convallis sit amet turpis.
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tempor vehicula ipsum nec ultrices. Pellentesque sed feugiat sapien.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tempor vehicula ipsum nec ultrices. Pellentesque sed feugiat sapien.  ullamcorper nunc. Aenean eget massa orci. Vivamus vulputate elit at rutrum elementum. Duis sit amet posuere justo, sit amet finibus urna. Aenean elementum diam nec laoreet sodales. Morbi vulputate tempor nisl nec tristique.</p>
			</div>
		</div>
	</div>
	<!-- //about-page -->

{% endblock content%}

templates/card.html
<div class="agile-products">
							<div class="new-tag"><h6>20%<br>Off</h6></div>
                            {% if instance.image %}
							<a href="{{ instance.get_absolute_url }}"><img src="{{ instance.image.url }}" class="img-responsive" alt="{{ instance.title }}"></a>
                            {% endif %}
							<div class="agile-product-text">
								<h5><a href="{{ instance.get_absolute_url }}">{{ instance.title }}</a></h5>
                                {% include "update-cart.html" with product=instance cart=cart %}
								<h6><del>$200</del> $100</h6>
							</div>
						</div>

templates/cart.html
{% extends 'base.html' %}
{% load l10n %}
{% load static %}
{% block content %}
    {% if cart.products.exists %}
        <table class="table cart-table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Product Name</th>
              <th scope="col">Product Price</th>
              <th scope="col">Edit</th>
            </tr>
          </thead>
          <tbody class="cart-body">
            {% for product in cart.products.all %}
                <tr class="cart-products">
                  <th scope="row">{{ forloop.counter }}</th>
                  <td><a href="{% url 'products:detail' product.slug %}">{{product.title}}</a></td>
                  <td>{{product.price|floatformat:2|localize }}</td>
                  <td>
                     {% include "carts/snippets/remove-product.html" with product_id=product.id cart=cart %}
                  </td>
                </tr>
            {% endfor %}
            <tr>
                <td colspan="3"></td>
                <td><b>Subtotal: </b> <span class="cart-subTotal">{{ cart.subtotal|floatformat:2|localize }}</span> ₺</td>
            </tr>
            <tr>
                <td colspan="3"></td>
                <td><b>Total: </b> <span class="cart-total">{{ cart.total|floatformat:2|localize }}</span> ₺</td>
            </tr>
            <tr>
                <td colspan="3"></td>
                <td><a class="btn btn-block btn-success" href="{% url 'carts:checkout' %}">Checkout</a></td>
            </tr>
          </tbody>
        </table>

        <div class="cart-item-remove-form" style="display: none">
            {% include 'carts/remove-product.html' %}
        </div>
    {% else %}
        <p class="lead">Cart is empty.</p>
    {% endif %}
{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content%}
<!-- breadcrumbs -->
	<div class="container">
		<ol class="breadcrumb breadcrumb1">
			<li><a href="{% url 'home' %}">Home</a></li>
			<li class="active">Single Page</li>
		</ol>
		<div class="clearfix"> </div>
	</div>
	<!-- //breadcrumbs -->


	<!-- products -->
	<div class="products">
		<div class="container">
			<div class="single-page">
				<div class="single-page-row" id="detail-21">
					<div class="col-md-6 single-top-left">
						<div class="flexslider">
							<ul class="slides">
								<li data-thumb="{{ object.image.url }}">
									<div class="thumb-image detail_images"> <img src="{{ object.image.url }}" data-imagezoom="true" class="img-responsive" alt=""> </div>
								</li>
								<li data-thumb="{{ object.image.url }}">
									 <div class="thumb-image"> <img src="{{ object.image.url }}" data-imagezoom="true" class="img-responsive" alt=""> </div>
								</li>
								<li data-thumb="{{ object.image.url }}">
								   <div class="thumb-image"> <img src="{{ object.image.url }}" data-imagezoom="true" class="img-responsive" alt=""> </div>
								</li>
							</ul>
						</div>
					</div>
					<div class="col-md-6 single-top-right">
						<h3 class="item_name">{{ object.title }}</h3>
						<div class="single-price">
							<ul>
								<li>{{ object.price }}</li>
								<li><del>$600</del></li>
								<li><span class="w3off">10% OFF</span></li>
							</ul>
						</div>
						<p class="single-price-text">{{ object.description }} </p>
			            {% include "update-cart.html" with product=object cart=cart %}
					</div>
				   <div class="clearfix"> </div>
				</div>
			</div>
		</div>
	</div>
	<!--//products-->

{% endblock content%}

templates/login.html
{% extends 'base.html' %}
{% block content %}
	<!-- login-page -->
	<div class="login-page">
		<div class="container">
			{% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
                      {{ message }}
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                {% endfor %}
            </ul>
        {% endif %}
			<h3 class="w3ls-title w3ls-title1">Login to your account</h3>

			<div class="login-body">
				<form method="POST">{% csrf_token %}
					{% if next_url %}
            		<input type="hidden" name="next" value="{{ next_url }}">
        			{% endif %}
					{{ form.as_p }}
			        <button type="submit" class="btn btn-success">Login</button>
				</form>
			</div>  
			<h6> Not a Member? <a href="{% url 'accounts:register' %}">Sign Up Now »</a> </h6>
		</div>
	</div>
	<!-- //login-page --> 
{% endblock content %}

templates/login_form.html
	<!-- login-page -->
	<div class="login-page col-md-12">
		<div class="container  col-md-12">
			<div class="login-body">
				<form action="{% if action_url %} {{ action_url }} {% else %} {% url 'accounts:login' %} {% endif %}" method="POST">
                    {% csrf_token %}
                    {% if next_url %}
					<input type="hidden"  name="next" value="{{ next_url }}">
                    {% endif %}
					{{ form.as_p }}
                    <button type="submit" class="btn btn-primary btn-success">Login</button>
				</form>
			</div>
		</div>
	</div>
	<!-- //login-page -->

templates/register.html
{% extends 'base.html' %}

{% block content %}

	<!-- sign up-page -->
	<div class="login-page">
		<div class="container">
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
                      {{ message }}
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                {% endfor %}
            </ul>
        {% endif %}
			<h3 class="w3ls-title w3ls-title1">Create your account</h3>
			<div class="login-body">
				<form method="POST">{% csrf_token %}
                    {% if next_url %}
                    <input type="hidden" name="next" value="{{ next_url }}">
                    {% endif %}
					{{ form.as_p }}
                    <button type="submit" class="btn btn-success">Register</button>
				</form>
			</div>
			<h6>Already have an account? <a href="login.html">Login Now »</a> </h6>
		</div>
	</div>
	<!-- //sign up-page -->

{% endblock content %}

templates/update-cart.html
{% url "carts:update" as cart_update_url %}

<form action="{% url 'carts:update' %}" method="POST" data-endpoint="{% url 'carts:home_api' %}">
    {% csrf_token %}
    <input type="hidden" name="product_id" value="{{ product.id }}" />
    {% if object in cart.products.all %}
      In Cart <button type="submit" class="btn btn-link">Remove </button>
    {% else %}
	<button type="submit" class="w3ls-cart" ><i class="fa fa-cart-plus" ></i> Add to cart</button>
     {% endif %}
</form>